apiVersion: apps/v1
kind: Deployment
metadata:
  name: room
  labels:
    app: room
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room
  template:
    metadata:
      labels:
        app: room
    spec:
      containers:
        - name: room
          image: "user07.azurecr.io/room:latest"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "210m"
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          env:
          - name: ORDER_LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: config-dev
                key: ORDER_LOG_LEVEL
          # volumeMounts:
          #   - mountPath: "/mnt/data"
          #     name: volume
      # volumes:
      #   - name: volume
      #     persistentVolumeClaim:
      #       claimName: azurefile 
